#### Data Encoding

In [5]:
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

In [5]:
df = pd.DataFrame({
    "colors": ['red', 'green', 'blue','blue','red', 'green']
})

In [6]:
df.head(6)

  colors
0    red
1  green
2   blue
3   blue
4    red
5  green

In [7]:
##  Create an instance of encoding 
encoder = OneHotEncoder()

In [8]:
encoded=encoder.fit_transform(df[['colors']]).toarray()

In [9]:
edf = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())

In [10]:
edf

   colors_blue  colors_green  colors_red
0          0.0           0.0         1.0
1          0.0           1.0         0.0
2          1.0           0.0         0.0
3          1.0           0.0         0.0
4          0.0           0.0         1.0
5          0.0           1.0         0.0

In [11]:
### Assignment
import seaborn as sns
ds=sns.load_dataset('tips')

In [12]:
ds

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [13]:
df = ds[['smoker']]

In [14]:
enc = OneHotEncoder()

In [15]:
encode = enc.fit_transform(df[['smoker']]).toarray()

In [16]:
smoker_df = pd.DataFrame(encode,columns= enc.get_feature_names_out())

In [17]:
smoker_df

     smoker_No  smoker_Yes
0          1.0         0.0
1          1.0         0.0
2          1.0         0.0
3          1.0         0.0
4          1.0         0.0
..         ...         ...
239        1.0         0.0
240        0.0         1.0
241        0.0         1.0
242        1.0         0.0
243        1.0         0.0

[244 rows x 2 columns]

In [2]:
import seaborn as sns
ds1 = sns.load_dataset('tips')

In [3]:
sdf=ds1[['sex']]

In [6]:
en = OneHotEncoder()

In [11]:
encode1 = en.fit_transform(sdf[['sex']]).toarray()

In [12]:
gender_DF=pd.DataFrame(encode1,columns=en.get_feature_names_out())

In [13]:
gender_DF

     sex_Female  sex_Male
0           1.0       0.0
1           0.0       1.0
2           0.0       1.0
3           0.0       1.0
4           1.0       0.0
..          ...       ...
239         0.0       1.0
240         1.0       0.0
241         0.0       1.0
242         0.0       1.0
243         1.0       0.0

[244 rows x 2 columns]

#### Label Encoding

In [1]:
from sklearn.preprocessing import LabelEncoder
lbl = LabelEncoder()

In [3]:
import pandas as pd
df = pd.DataFrame({
    'colors':['red', 'green', 'blue','red', 'green', 'blue']
})

In [9]:
encoded = lbl.fit_transform(df['colors'])

In [14]:
lbl.transform([['blue']])

d:\Data BootCamp\Python\venv\lib\site-packages\sklearn\preprocessing\_label.py:129: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)

array([0])

### Ordinal Encoding

In [15]:
from sklearn.preprocessing import OrdinalEncoder

In [16]:
oDF = pd.DataFrame({
    "size":['small','medium','large','small','medium','large']
})

In [21]:
ode = OrdinalEncoder(categories=[['small','medium','large']])

In [22]:
encoded = ode.fit_transform(oDF[['size']])

In [ ]:
ode.transform([['small']])

d:\Data BootCamp\Python\venv\lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])

### Target Guided Ordinal Encoding

In [1]:
import pandas as pd
tdf = pd.DataFrame({
    'city':['khi','lhr','btk', 'khi'],
    'price':[2000,3000,4000,2200]
})

In [2]:
tdf

  city  price
0  khi   2000
1  lhr   3000
2  btk   4000
3  khi   2200

In [ ]:
from sklearn.preprocessing import TargetEncoder

In [5]:
meanPrice=tdf.groupby('city')['price'].mean().to_dict()

In [6]:
tdf['encoded_city']=tdf['city'].map(meanPrice)

In [7]:
tdf

  city  price  encoded_city
0  khi   2000        2100.0
1  lhr   3000        3000.0
2  btk   4000        4000.0
3  khi   2200        2100.0